import './global.css';

export const metadata = {
  title: 'Welcome to incident-tracker',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-row w-full">
          <aside className="fixed left-0 top-0 w-64 bg-slate-100 px-5 h-screen">
            <div className="flex flex-col">
              <h2>Side Bar</h2>
            </div>
          </aside>
          {children}
        </main>
      </body>
    </html>
  );
}
